name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Test applogger
      run: go test -v ./applogger/...

    - name: Test devologtable
      run: go test -v ./devologtable/...

    - name: Test devoquery
      run: go test -v ./devoquery/...

    - name: Test devosender
      run: go test -v ./devosender/...
